print (3+4)
print (3-4)
print (3*4)
print (3%4)
print (3%4)
print (3/4)
print (10%2)
print (3**4)
print (3//4)
print ('Ali')
print ('Pakistan')
print ('I am enjoying 30 days of python')
print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type(['Asabnehe','Pyrhon','finland']))
print(type('shahzaib'))
print(type('pakistan'))
print(['shahzaib',21])

